#!/bin/bash

echo "🚀 AMADEUS PRODUCTION - Quick Start"
echo "===================================="
echo ""
echo "📋 PASO 1: Solicitar Production Access"
echo ""
echo "1. Abre tu navegador:"
echo "   https://developers.amadeus.com"
echo ""
echo "2. Inicia sesión con tu cuenta"
echo ""
echo "3. Ve a: My Self-Service Workspace"
echo ""
echo "4. Click: Request Production Access"
echo ""
echo "5. Completa el formulario:"
echo "   - App Name: Biajez Flight Booking Platform"
echo "   - Type: Flight Search & Booking"
echo "   - Volume: 500-1,000 searches/month"
echo "   - Use Case: AI-powered OTA for LATAM"
echo ""
echo "6. Submit y espera 1-3 días"
echo ""
echo "===================================="
echo "📧 PASO 2: Cuando Recibas Aprobación"
echo ""
echo "1. Ve a: https://developers.amadeus.com/my-apps"
echo ""
echo "2. Click en tu app"
echo ""
echo "3. Tab 'Production'"
echo ""
echo "4. Copia:"
echo "   - API Key (Client ID)"
echo "   - API Secret"
echo ""
echo "5. Ejecuta:"
echo "   ./configure_amadeus_production.sh"
echo ""
echo "===================================="
echo ""
echo "💡 TIP: Guarda este script para referencia"
echo ""
